%macro rm_design(ds=ds, cluster=center,trt=trt, period=period);
* gives overview of number of subject in each period and their treatment assignment; 
title4 "treatments applied per cluster-period";
title4 "check whether each cluster-period has one treatment?";
proc tabulate data=&ds;class &cluster &period &trt;format &period 4.0; 
table &cluster*&trt, &period*N*f=4. /rts=15 ;
run;
%mend;

%macro sw_cont_descrip(ds=ds,outcome=, cluster=center, period=period, trt=trt,
outcome_min=-1000, outcome_max=+1000,period_min=1,period_max=14,dsdescrip=);
* gives descriptives for repeated measures of a continuous outcome;

*get outcome label;
data _null_; set &ds; call symput('outcome_label', vlabel(&outcome));run;
title3 "description   ****&outcome: &outcome_label *****";
title4 "all values";
proc means data=&ds n nmiss min max p5 p95 Q1 median Q3 mean std; var &outcome; run; 
proc sgpanel data=&ds;  
panelby &cluster / onepanel;
histogram &outcome;
run;
title4 "data size per cluster-period";
proc tabulate data=&ds; class &cluster &period; var &outcome;
table &cluster, &period="&outcome: N per cluster-period"*&outcome=' '*(N=' ')*f=5.0 / rts=10;  run;
title4 "mean per cluster-period";
proc tabulate data=&ds; class &cluster &period; var &outcome;
table &cluster, &period="&outcome: mean per cluster-period"*&outcome=' '*(mean=' ')*f=5.2 / rts=10;  run;

title3 "analysis    ****&outcome: &outcome_label ****";
title4 "time series plot per cluster)";
title5 "(note: periods with trt=0 and 1 are considered trt=1";
proc means data=&ds noprint; id &trt; class &cluster &period;
var &outcome; output out=_ClusPeriodMeans mean(&outcome)=mean;run;
proc sgpanel data=_clusPeriodmeans;
panelby &cluster / onepanel; *or columns=1 to get only one column;
series x=&period y=mean;
scatter x=&period y=mean /group=&trt markerattrs=(size=9) ;
rowaxis integer min=&outcome_min max=&outcome_max alternate;
colaxis min=&period_min max=&period_max alternate integer;
run;
* to do: time series analysis per cluster using standard techniques?*;
title4 "disregarding possible time trend:";
proc means data=&ds n nmiss min max p5 p95 Q1 median Q3 mean std; class &trt;var &outcome; run;
data _shift; set &ds;
if &trt=1 then intervention_&outcome=&outcome; 
if &trt=0 then control_&outcome=&outcome;
run;
title5 "shift in distribution by intervention: over *all* clusters";
proc sgplot data=_shift;
histogram intervention_&outcome /transparency=0.3;
histogram control_&outcome /transparency=0.6;
run;
title5 "shift in distribution by intervention: by cluster";
proc sgpanel data=_shift;  
panelby &cluster / onepanel;
histogram intervention_&outcome /transparency=0.3;
histogram control_&outcome /transparency=0.6;
run;
title5 "shift in means, medians, boxplots"; 
proc sgpanel data=&ds;  
panelby &cluster / onepanel;
*vbar &trt / response=&outcome stat=mean;
hbox &outcome / category=&trt;
run;
*show descriptives and if need save them***;
proc means data=&ds n nmiss mean std median Q1 Q3; var &outcome; class &trt;
%IF &dsdescrip ne %THEN %DO; 
output out=_descrip n=n nmiss=nmiss mean=mean std=std median=median Q1=Q1 Q3=Q3 ;
%END;
run;
%IF &dsdescrip ne %THEN %DO; 
data _descrip; length outcome $30; length outcome_label $ 100; length stat $ 10;
set _descrip; outcome="&outcome";outcome_label="&outcome_label";
array aux[7] n nmiss mean std median Q1 Q3; 
do i=1 to 7;
stat=vname( aux[i]); value=aux[i];output;
end; 
drop  n nmiss mean std median Q1 Q3; 
if _type_=1;
keep outcome outcome_label &trt stat value;
run;
proc append force base=&dsdescrip data=_descrip;run;
%END;
%mend sw_cont_descrip;

*** mock subject-within-cluster-period data for the descriptive macros;
*** two centers, 12 periods, a few subjects per cluster-period, a continuous outcome;
*** trt switches on partway through in a stepped-wedge fashion;
data ds;
  call streaminit(20240124);
  label score = "symptom score";
  do center = 1 to 2;
    switch = 5 + center;
    do period = 1 to 12;
      trt = (period >= switch);
      do subj = 1 to 4;
        score = 20 - 0.3*period - 3*trt + rand("normal", 0, 2);
        output;
      end;
    end;
  end;
  drop switch subj;
run;

title2 "design overview: subjects per cluster-period and treatment assignment";
%rm_design(ds=ds, cluster=center, trt=trt, period=period);

title2 "descriptives for the continuous outcome across cluster-periods";
%sw_cont_descrip(ds=ds, outcome=score, cluster=center, period=period, trt=trt,
                 outcome_min=0, outcome_max=28, period_min=1, period_max=12);
